import { StyleSheet } from 'react-native';
import { useAppTheme } from '../../hooks/useAppTheme';

export const useCartScreenStyles = () => {
  const theme = useAppTheme();
  return StyleSheet.create({
    container: {
      flex: 1,
      paddingVertical: 12,
      paddingHorizontal: 8,
      backgroundColor: theme.colors.surface,
    },
    headerSection: {
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
    },
    header: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.text,
    },
    emptyBtnContainer: {
      backgroundColor: theme.colors.surfaceVariant,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      borderColor: theme.colors.border,
      borderWidth: 0.3,
      elevation: 2,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    cartListContainer: {
      flex: 1,
      minHeight: 0,
      borderRadius: 12,
      overflow: 'hidden',
    },
    cartList: {
      flex: 1,
      borderRadius: 12,
      backgroundColor: theme.colors.surface,
    },
    cartListContent: {
      paddingHorizontal: 2,
      paddingVertical: 4,
    },
    emptyTextMsgContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      backgroundColor: theme.colors.surfaceVariant,
      padding: 20,
      borderColor: theme.colors.border,
      borderWidth: 0.3,
      elevation: 2,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    emptyIconContainer: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    emptyIcon: {
      color: theme.colors.primary,
    },
    emptyText: {
      textAlign: 'center',
      marginTop: 20,
      fontSize: 16,
      color: theme.colors.text,
      fontWeight: '200',
      marginBottom: 6,
    },
    emptyLinkText: {
      color: theme.colors.primary,
      fontWeight: '200',
    },
    cartItemShadow: {
      marginHorizontal: 2,
      elevation: 2,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      borderRadius: 10,
    },
    cartItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.card,
      borderRadius: 10,
      overflow: 'hidden',
      borderColor: theme.colors.border,
      borderWidth: 0.2,
    },
    cartItemSeparator: {
      backgroundColor: theme.colors.border,
      marginVertical: 4,
    },
    thumbnailContainer: {
      width: 64,
      height: 64,
      overflow: 'hidden',
      marginRight: 10,
      backgroundColor: `${theme.colors.primary}1A`,
      borderBottomRightRadius: 8,
    },
    productImage: {
      width: '100%',
      height: '100%',
    },
    itemInfo: {
      flex: 1,
      padding: 4,
      paddingRight: 20,
    },
    itemName: {
      fontSize: 15,
      fontWeight: '300',
      marginBottom: 4,
      color: theme.colors.text,
    },
    itemPrice: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 2,
      fontWeight: '300',
    },
    quantitySection: {
      alignItems: 'flex-end',
    },
    quantity: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      marginBottom: 4,
      fontWeight: '300',
    },
    itemTotal: {
      fontSize: 14,
      fontWeight: '400',
      color: theme.colors.textSecondary,
    },
    divider: {
      height: 1,
      backgroundColor: theme.colors.border,
      marginVertical: 16,
    },
    summaryShadow: {
      marginTop: 8,
      marginHorizontal: 2,
      marginBottom: 8,
      elevation: 2,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      borderRadius: 10,
      backgroundColor: theme.colors.card,
    },
    summaryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 10,
    },
    summaryHeaderTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.text,
    },
    summaryHeaderSubtitle: {
      marginTop: 2,
      fontSize: 12,
      color: theme.colors.textSecondary,
    },
    summaryContainer: {
      paddingTop: 12,
      paddingHorizontal: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 10,
      borderTopWidth: 0.5,
      borderTopColor: theme.colors.primary,
      borderColor: theme.colors.border,
      zIndex: 2,
      marginBottom: 8,
    },
    summary: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    summaryLabel: {
      fontSize: 14,
      color: theme.colors.textSecondary,
    },
    summaryValue: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.text,
    },
    totalSection: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    totalLabel: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.colors.text,
    },
    totalPrice: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.colors.primary,
    },
    shippingCheckboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    checkoutButton: {
      backgroundColor: theme.colors.primary,
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: 'center',
    },
    checkoutText: {
      color: theme.colors.accent,
      fontSize: 16,
      fontWeight: '400',
    },
    priceQuantityContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
  });
};
