import { StyleSheet } from 'react-native';
import { useAppTheme } from '../../hooks/useAppTheme';

export const useProductDetailsScreenStyles = () => {
  const theme = useAppTheme();

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.text,
    },
    imageContainer: {
      margin: 16,
      borderRadius: 16,
      backgroundColor: theme.colors.surfaceVariant,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      position: 'relative',
      minHeight: 260,
      elevation: 2,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      borderColor: theme.colors.border,
      borderWidth: 0.2,
    },
    productImage: {
      width: '100%',
      height: 240,
    },
    wishlistButton: {
      position: 'absolute',
      top: 12,
      right: 12,
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
      borderWidth: 0.5,
      borderColor: theme.colors.border,
    },
    detailsContainer: {
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    nameRatingContainer: {
      marginBottom: 8,
    },
    productName: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.colors.text,
      marginBottom: 8,
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    ratingText: {
      fontSize: 13,
      color: theme.colors.textSecondary,
      fontWeight: '400',
    },
    categoryText: {
      alignSelf: 'flex-start',
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.primary,
      backgroundColor: `${theme.colors.primary}1A`,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      marginBottom: 12,
      textTransform: 'capitalize',
    },
    priceContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 16,
    },
    price: {
      fontSize: 24,
      fontWeight: '700',
      color: theme.colors.primary,
    },
    originalPrice: {
      fontSize: 16,
      color: theme.colors.textDisabled,
      textDecorationLine: 'line-through',
    },
    descriptionContainer: {
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.text,
      marginBottom: 8,
    },
    descriptionText: {
      fontSize: 14,
      lineHeight: 22,
      color: theme.colors.textSecondary,
      fontWeight: '400',
    },
    specificationsContainer: {
      marginBottom: 16,
      padding: 12,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceVariant,
    },
    specRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 6,
      borderBottomWidth: 0.5,
      borderBottomColor: theme.colors.border,
    },
    specLabel: {
      fontSize: 14,
      color: theme.colors.textSecondary,
      flex: 1,
      marginRight: 8,
    },
    specValue: {
      fontSize: 14,
      color: theme.colors.text,
      fontWeight: '500',
      flexShrink: 1,
      textAlign: 'right',
    },
    quantityContainer: {
      marginBottom: 16,
    },
    quantitySelector: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      borderRadius: 12,
      borderWidth: 0.2,
      borderColor: theme.colors.border,
      overflow: 'hidden',
      backgroundColor: theme.colors.surface,
      elevation: 2,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    quantityButton: {
      width: 42,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceVariant,
    },
    quantityText: {
      minWidth: 52,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.text,
    },
    stockContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 16,
    },
    stockText: {
      fontSize: 14,
      fontWeight: '500',
    },
    goToCartButton: {
      position: 'absolute',
      left: 16,
      right: 16,
      bottom: 16,
      height: 52,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 10,
      elevation: 3,
    },
    addToCartButton: {
      justifyContent: 'center',
      flexDirection: 'row',
      alignSelf: 'flex-start',
      gap: 8,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 10,
      elevation: 3,
      backgroundColor: theme.colors.secondary,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 12,
      marginBottom: 14,
    },
    addToCartIcon: {
      color: theme.colors.accent,
    },
    addToCartText: {
      color: theme.colors.accent,
      fontSize: 16,
      fontWeight: '600',
    },
    goToCartText: {
      color: theme.colors.accent,
      fontSize: 16,
      fontWeight: '600',
    },
    bottomSpace: {
      paddingBottom: 100,
    },
    loadingText: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textDisabled,
    },
  });
};
